### ISSUE TITLE
None of the vSphere ubuntu-xenial 170.* stemcells work with ECS service broker 1.2.0

### ISSUE THREAD

**Issue by dataghoti** [pivotal-cf/docs-ecs-service-broker#15]
Tried:
170.13
170.15
170.19
170.23
170.24
170.25

All resulted in the same terse unhelpful error: "File is invalid."

**Comment by jncd** [comment]
Hi @dataghoti ,

This documentation repository is maintained by technical writers, not developers or support engineering. For questions about the ECS Service Broker for PCF, it is best to contact ECS Customer Support (ecstiles-support@dell.com). 
That said, I have tried to escalate your issue through the PCF ISV manager and you might receive an answer from them in a few days. In the meantime, you might try emailing support directly.

Best regards, Jane
